program_options:
  tray: auto
  notify: true
  menu: flat
  automount: true
  file_manager: yazi

notifications:
  timeout: 1.5           # Notification timeout in seconds
  device_mounted: 5      # Show mount notifications for 5
